# Generated by Django 3.2.8 on 2021-11-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('pDescription', models.CharField(max_length=200)),
                ('pProduceDate', models.DateTimeField()),
                ('pExpireDate', models.DateTimeField()),
                ('pImage', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('pBuyPrice', models.FloatField()),
                ('pSellPrice', models.FloatField()),
                ('pCategories', models.CharField(choices=[('tablets', 'tablets'), ('injection', 'injection'), ('drink', 'drink')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCompanyName', models.CharField(max_length=50)),
                ('sAddress', models.CharField(max_length=100)),
                ('sMobile', models.IntegerField()),
                ('sCity', models.CharField(max_length=50)),
                ('sSalesName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=50)),
                ('uAddress', models.CharField(max_length=200)),
                ('uMobile', models.IntegerField()),
                ('uImage', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('uGender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rDate', models.DateTimeField(auto_now_add=True)),
                ('rQuantity', models.IntegerField()),
                ('rTotalPrice', models.FloatField()),
                ('rProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.products')),
                ('rSupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oDate', models.DateTimeField(auto_now_add=True)),
                ('oQuantity', models.IntegerField()),
                ('oTatalPrice', models.FloatField()),
                ('oCategories', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for Delivered', 'Out for Delivered')], max_length=20)),
                ('oCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.user')),
                ('oProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.products')),
            ],
        ),
    ]
