# Generated by Django 3.2.8 on 2021-11-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFullName', models.CharField(max_length=50)),
                ('CAddress', models.CharField(max_length=200)),
                ('CMobile', models.IntegerField()),
                ('CImage', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('CGender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('CEmail', models.CharField(max_length=30, null=True)),
                ('CUserName', models.CharField(max_length=50, null=True)),
                ('CPassword', models.CharField(max_length=30, null=True)),
                ('Cuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('pDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('pProduceDate', models.DateTimeField()),
                ('pExpireDate', models.DateTimeField()),
                ('pImage', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('pBuyPrice', models.FloatField()),
                ('pSellPrice', models.FloatField()),
                ('pConcentration', models.FloatField(default=100)),
                ('pCategories', models.CharField(choices=[('tablets', 'tablets'), ('injection', 'injection'), ('drink', 'drink')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCompanyName', models.CharField(max_length=50)),
                ('sAddress', models.CharField(max_length=100)),
                ('sMobile', models.IntegerField()),
                ('sCity', models.CharField(max_length=50)),
                ('sSalesName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rDate', models.DateTimeField(auto_now_add=True)),
                ('rQuantity', models.IntegerField()),
                ('rTotalPrice', models.FloatField()),
                ('rProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.products')),
                ('rSupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.suppliers')),
            ],
        ),
    ]
