# Generated by Django 3.2.8 on 2021-11-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oDate', models.DateTimeField(auto_now_add=True)),
                ('oQuantity', models.IntegerField()),
                ('oTatalPrice', models.FloatField()),
                ('oCategories', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for Delivered', 'Out for Delivered')], max_length=20)),
                ('oCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.customer')),
                ('oProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.products')),
            ],
        ),
    ]
