# Generated by Django 3.2.8 on 2021-11-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pConcentration',
            field=models.FloatField(default=100),
        ),
    ]
