# Generated by Django 3.2.8 on 2021-11-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CFullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CPassword',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CUserName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
