# Generated by Django 3.2.8 on 2021-11-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0003_alter_products_pdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFullName', models.CharField(max_length=50)),
                ('CAddress', models.CharField(max_length=200)),
                ('CMobile', models.IntegerField()),
                ('CImage', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('CGender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('CEmail', models.CharField(max_length=30, null=True)),
                ('CUserName', models.CharField(max_length=50, null=True)),
                ('CPassword', models.CharField(max_length=30, null=True)),
                ('Cuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='oCustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.customer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
